#include <iostream>
#include <cassert>
#include <vector>
#include <set>
#include <array>
#include <iostream>
#include <fstream>
#include <cstring>
#include <sstream>
#include <map>
#include <utility>
#include <algorithm>
#include "../../glm/glm.hpp"
#include "Log/Log.h"
#include "../../third-party/shaderc/include/shaderc/shaderc.hpp"
#include "../../third-party/stb/stb_image.h"
//#include "../../third-party/vma/vk_memory_alloc.h"
#include "../vk_loader/inc/vk_loader.h"
#include "vk_framework_enums.h"
#include "vk_framework_structs.h"
#include "../third-party/glfw-3.3.8/include/GLFW/glfw3.h"
#include "utils/platform/Window.h"
#include "windowconfig.h"
#include "vulkan/vk_enum_string_helper.h"
#include "utils/vk_instance_and_device_utils.h"
#include "utils/vk_layer_and_extension_utils.h"
#include "utils/platform/Linux/vk_render_surface.h"
#include "utils/vk_swapchain_utils.h"
#include "utils/vk_command_X_utils.h"
#include "utils/vk_shader_utils.h"
#include "utils/vk_render_X_utils.h"
#include "utils/resources/buffer/vk_buffer_util.h"
#include "utils/resources/image/vk_image_util.h"
#include "asset_utils.h"
#include "config.h"
#include "utils/sync/semaphores/vk_semaphore_utils.h"
#include "utils/sync/fences/vk_fence_utils.h"
#include "utils/vk_descriptor_util.h"
#include "utils/resources/image/texture_util.h"
#include "utils/resources/image/depth_util.h"
#include "../../third-party/spirv-reflect/spirv_reflect.h"
#include "utils/spv_reflect_util.h"
#include "utils/vk_draw_utils.h"
#include "../inc/utils/resources/image/Texture2D.h"
#include "GpuRenderPass.h"
#include "DrawSetup.h"
#include "vk_framework.h"